project:
  name: PhoberNer

data_paths:
  train: ./data/raw/train.txt
  validation: ./data/raw/valid.txt
  test: ./data/raw/test.txt

model_paths:
  fine_tuned: ./model/fine_tuned

training:
  output_dir: ./phobert-ner
  evaluation_strategy: epoch
  learning_rate: 0.00001  
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  num_train_epochs: 3
  weight_decay: 0.01              

label_map:
  O: 0
  B-ASSIGNEE: 1
  B-TASK: 2
  B-DEADLINE: 3
  I-ASSIGNEE: 4
  I-TASK: 5
  I-DEADLINE: 6
