project:
  name: fine_tune_phobert_ner

paths:
  data_raw: data/raw/
  data_processed: data/processed/
  model_pretrained: models/pre_trained/
  model_fine_tuned: models/fine_tuned/

training:
  max_length: 256                 # Độ dài tối đa của câu sau khi tokenize
  batch_size: 16                  # Batch size cho huấn luyện và đánh giá
  learning_rate: 2e-5             # Learning rate cho optimizer AdamW
  num_epochs: 5                   # Số epoch huấn luyện

labels:
  - O                             # Không thuộc thực thể nào (Outside)
  - B-PERSON                     # Bắt đầu thực thể PERSON (Begin)
  - I-PERSON                     # Tiếp tục thực thể PERSON (Inside)
  - B-TASK                       # Bắt đầu thực thể TASK (Begin)
  - I-TASK                       # Tiếp tục thực thể TASK (Inside)
  - B-DATE                       # Bắt đầu thực thể DATE (Begin)
  - I-DATE                       # Tiếp tục thực thể DATE (Inside)
